### PR TITLE
joystick: add a joystick naming compatibility hint and API call

### PR DESCRIPTION
**Pull request by cmitu**
Starting with 2.0.12, SDL aplies some normalization to the joystick names, which results in the naming being different from what Linux's event/udev APIs report.
This causes issues for the EmulationStation's input mapping scripts, which assume the names (SDL vs. Linux) are identical (see for instance [RetroPie-Setup#3398](https://github.com/RetroPie/RetroPie-Setup/issues/3398).

The PR adds 2 commits:
- introduce a hint for SDL to use the old/pre-2.0.12) compatible joystick naming (`SDL_HINT_JOYSTICK_USE_OLD_NAME`, 0=false, 1=true).  By default, the hint is set to _true_ (i.e. the compatible naming is used by default).
- add a `SDL_JoystickCompatName` function that will always return the pre-2.0.12 joystick name, regardless of the value of the hint above. This helps application retrieve the previously used joystick name.

### CODE REVIEW

**Comment by cmitu** [comment]
OK, fixed a build failure on non-Linux, should be ok.
I've modified `test/testjoystick.c` to show both the new and old names during testing:

**Old naming** :
``` sh
SDL_JOYSTICK_USE_OLD_NAME=1 ./testjoystick 
INFO: Joystick device 0 added.
INFO: Joystick
INFO:        name: 'USB,2-axis 8-button gamepad  '
INFO:    old name: 'USB,2-axis 8-button gamepad  '
INFO:        type: Game Controller
INFO:        axes: 2
INFO:       balls: 0
INFO:        hats: 0
INFO:     buttons: 8
INFO: instance id: 0
INFO:        guid: 03000000830500006020000010010000
INFO:     VID/PID: 0x0583/0x2060
```

**New/Upstream naming** :
``` sh
SDL_JOYSTICK_USE_OLD_NAME=0 ./testjoystick 
INFO: Joystick device 0 added.
INFO: Joystick
INFO:        name: 'USB,2-axis 8-button gamepad'
INFO:    old name: 'USB,2-axis 8-button gamepad  '
INFO:        type: Game Controller
INFO:        axes: 2
INFO:       balls: 0
INFO:        hats: 0
INFO:     buttons: 8
INFO: instance id: 0
INFO:        guid: 03000000830500006020000010010000
INFO:     VID/PID: 0x0583/0x2060

**Comment by cmitu** [comment]
Some notes on the impact of the `SDL_JoystickName` and the changes in the PR:

* the SDL Gamecontroller subsystem shouldn't be impacted, the mapping db uses the device's GUID.
* older ES configs would also not be affected on upgrade when using the 'new' names, since the device's GUID is used for identification.
* the `retroarch` configs with new names would still work _if_ the vendor/product IDs are added to the generated `.cfg`. We could update ES to include the PID/VID and adjust the input configuration scripts to include it. Other input mapping scripts may need also adjusting to see which are using SDL or 'Linux' names (e.g. `mupen64plus` , `reicast` etc.)

**Comment by joolswills** [comment]
I'm thinking the second patch is going to a pain to maintain as this code may change a lot in the future.

The patch needs some work for 2.0.18 due to the addition of FreeJoylistItem / RemoveJoylistItem although FreeJoylistItem would enable less need for the additional frees.

Why do we need a function to get the compatible name ? I wonder if really it's needed vs the maintainability.

**Comment by cmitu** [comment]
> Why do we need a function to get the compatible name ? I wonder if really it's needed vs the maintainability.

The reasoning was that we could switch off the compatibility hint and use the new SDL names, but we'd need the old/compat name for:
* migrating existing ES configuration, when the SDL version changes with the new default
* obtaining the `udev` compatible name for auto-configuration scripts which need it (i.e. RetroArch)

**Comment by decosta707** [comment]
@cmitu  are you still around?  total noob learning a lot here.  is there  a script you run to make these changes? or do they have to modified individually? if there is where do you run it ? lol terminal? or ES environment?  just trying to play some games  with a controller

Please help

**Pull request merged**
